# Generated by Django 3.2 on 2021-05-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_realsimulation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realsimulation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
