# Generated by Django 3.2 on 2021-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_realsimulation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realsimulationchoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('currency', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=255)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('days50', models.FloatField(blank=True, null=True)),
                ('days150', models.FloatField(blank=True, null=True)),
                ('days200', models.FloatField(blank=True, null=True)),
                ('weeks20', models.FloatField(blank=True, null=True)),
                ('stdev', models.FloatField(blank=True, null=True)),
                ('bb', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
