# Generated by Django 3.2 on 2021-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_realsimulationchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fandamental',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('uriage20_19', models.FloatField(blank=True, null=True)),
                ('uriage19_18', models.FloatField(blank=True, null=True)),
                ('rieki20_19', models.FloatField(blank=True, null=True)),
                ('rieki19_18', models.FloatField(blank=True, null=True)),
                ('eps20_19', models.FloatField(blank=True, null=True)),
                ('eps19_18', models.FloatField(blank=True, null=True)),
                ('uriageshihanki213_212', models.FloatField(blank=True, null=True)),
                ('uriageshihanki212_211', models.FloatField(blank=True, null=True)),
                ('uriageshihanki211_204', models.FloatField(blank=True, null=True)),
                ('rieki213_212', models.FloatField(blank=True, null=True)),
                ('rieki212_211', models.FloatField(blank=True, null=True)),
                ('rieki211_204', models.FloatField(blank=True, null=True)),
                ('eps213_212', models.FloatField(blank=True, null=True)),
                ('eps212_211', models.FloatField(blank=True, null=True)),
                ('eps211_204', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
