# Generated by Django 3.2 on 2021-05-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_fandamental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fandamental',
            old_name='eps19_18',
            new_name='epsshihanki1',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='eps20_19',
            new_name='epsshihanki2',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='eps211_204',
            new_name='epsshihanki3',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='eps212_211',
            new_name='epstuuki1',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='eps213_212',
            new_name='epstuuki2',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='name',
            new_name='meigara',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='rieki19_18',
            new_name='riekishihanki1',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='rieki20_19',
            new_name='riekishihanki2',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='rieki211_204',
            new_name='riekishihanki3',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='rieki212_211',
            new_name='riekituuki1',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='rieki213_212',
            new_name='riekituuki2',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='uriage19_18',
            new_name='uriageshihanki1',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='uriage20_19',
            new_name='uriageshihanki2',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='uriageshihanki211_204',
            new_name='uriageshihanki3',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='uriageshihanki212_211',
            new_name='uriagetuuki1',
        ),
        migrations.RenameField(
            model_name='fandamental',
            old_name='uriageshihanki213_212',
            new_name='uriagetuuki2',
        ),
    ]
